srcs  = main.c
target = m.elf
include ../../../mk/common.mk
include ../../../mk/m.mk
LDFLAGS += $(MAKEFILE_DIR)../riscv-probe/build/obj/rv32imac/env/qemu-sifive_u/crt.o \
           $(MAKEFILE_DIR)../riscv-probe/build/obj/rv32imac/env/qemu-sifive_u/setup.o
 
